/**
 * mysql类型 映射 js类型
 */
export default {
  bigint: 'Number',
  binary: 'Number',
  bit: 'Number',
  blob: 'String',
  char: 'String',
  date: 'Date',
  datetime: 'Date',
  decimal: 'Number',
  double: 'Number',
  enum: 'String',
  float: 'Number',
  geometry: 'String',
  geometrycollection: 'String',
  int: 'Number',
  integer: 'Number',
  json: 'String',
  linestring: 'String',
  longblob: 'String',
  longtext: 'String',
  mediumblob: 'String',
  mediumint: 'Number',
  mediumtext: 'String',
  multilinestring: 'String',
  multipoint: 'String',
  multipolygon: 'String',
  numeric: 'Number',
  point: 'String',
  polygon: 'String',
  real: 'Number',
  set: 'String',
  smallint: 'Number',
  text: 'String',
  time: 'String',
  timestamp: 'Number',
  tinyblob: 'String',
  tinyint: 'Number',
  tinytext: 'String',
  varbinary: 'String',
  varchar: 'String',
  year: 'String',
}
